language: java
jdk:
  - oraclejdk9
  - openjdk9
  - oraclejdk8
  - openjdk8
sudo: required
dist: trusty
before_install:
  - echo Setting up workspace...
  - chmod +x gradlew
  - ls -a -l -h --color
  - echo Downloading Gradle
  - ./gradlew
  - ./gradlew -version
install:
  - ./gradlew assemble
before_script:
  - echo Starting building process
  - ./gradlew dependencies
script:
  - ./gradlew check --info
after_success:
  - echo Build successful
  - ./gradlew build --info
after_failure:
  - echo Build failed
after_script:
  - echo Build terminated.
notifications:
  email:
    recipients:
      - thesilkminer@outlook.com
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always